[package]
name = "seamless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = {version="1.1.3", optional = true}
ipnetwork = "0.20.0"
network-interface = "1.0.3"


[features]
send=["dep:device_query"]
